name: GraalVM Native Image build

on:
  push:
    branches: [ main ]
    tags: [ "v*.*.*" ]

jobs:
  buildOnLinux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 16
          graalvm-version: 21.2.0
          native-image: true
      - name: Build with Maven
        run: mvn -B clean verify --file pom.xml
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1
        with:
          version: latest
          file: target/frids
          args: '-9'
      - uses: actions/upload-artifact@v2
        with:
          name: frids
          path: target/frids
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')